version: '3'
services:
  mongodb:
    restart: always
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  redisdb:
    restart: always
    container_name: redisdb
    image: redis
    ports:
      - "6379:6379"

  mancala:
    restart: always
    container_name: mancala
    image: mancala:v1
    build: ./mancala/
    depends_on:
      - redisdb
      - mongodb
    environment:
      - MANCALA_PIT_STONES=6
      - SPRING_APPLICATION_NAME=mancala
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_REDIS_HOST=redisdb
      - SPRING_REDIS_PORT=6379
      - MANCALA_API_SERVICE_ID= mancala
    volumes:
      - ~/docker/mancala:/mancala/logs
    ports:
      - "8082:8080"

  mancalaui:
    restart: always
    container_name: mancalaui
    image: mancalaui:v1
    build: ./mancala-ngx/
    depends_on:
      - mancala
    volumes:
      - ~/docker/mancala:/mancala/logs
    ports:
      - "8083:80"